[tool.poetry]
name = "info"
version = "0.1.0"
description = ""
authors = ["Joshua Oliphant <joshua.oliphant@hey.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
textual-dev = "^0.0.2"
rich = "^13.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
