[tool.poetry]
name = "avocet"
version = "0.1.0"
description = "A TUI for Raindrop.io bookmarks written in Python"
authors = ["Joshua Oliphant <joshua.oliphant@hey.com>"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.11"
textual-dev = "^0.0.2"
rich = "^13.1.0"
textual = "^0.19.0"
httpx = "^0.23.3"
pytest = "^7.3.0"
pytest-mock = "^3.10.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"
pytest-httpx = "^0.21.3"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
