[tool.poetry]
name = "avocet"
version = "0.1.0"
description = ""
authors = ["Joshua Oliphant <joshua.oliphant@hey.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
textual-dev = "^0.0.2"
rich = "^13.1.0"
textual = "^0.19.0"
httpx = "^0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
